# Generated by Django 5.0.6 on 2024-07-04 16:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(max_length=9, unique=True, validators=[django.core.validators.MinLengthValidator(9)], verbose_name='Phone Number'),
        ),
    ]
